# Ubuntu 22.04 이미지 사용
FROM ubuntu:22.04

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
	curl \
    wget \
    git \
    build-essential \
    vim \
    python3 \
    python3-pip \
    net-tools \
    iputils-ping \
    unzip \
    tar \
    htop \
    gnupg \
    software-properties-common

WORKDIR /app


